## Componentes fundamentales

Un HMM se define mediante tres parámetros principales: $\pi$, $A$ y $B$.

1. **$\pi$ (distribución inicial):** Es un vector que contiene la probabilidad de que el sistema comience en cada uno de los estados ocultos. Es decir,

   $$
   \pi_i=P(q_1=i),
   $$

   donde $q_1$ representa el estado inicial.

2. **$A$ (matriz de transición):** Describe las probabilidades de transición entre los estados ocultos del modelo. Cada elemento

   $$
   a_{ij}=P(q_{t+1}=j \mid q_t=i)
   $$

   representa la probabilidad de que el sistema pase del estado $i$ al estado $j$ en el siguiente instante de tiempo.

   La matriz $A$ tiene dimensiones

   $$
   N\times N,
   $$

   donde $N$ es el número de estados ocultos.

   En esta matriz:

   - **Cada renglón representa el estado actual** del sistema, es decir, el estado en el instante $t$.
   - **Cada columna representa el estado siguiente**, es decir, el estado en el instante $t+1$.
   - El elemento ubicado en el renglón $i$ y la columna $j$ indica la probabilidad de realizar la transición

     $$
     i\rightarrow j.
     $$

   Por ejemplo, si los estados ocultos son

   $$
   1=\text{Resfriado},\qquad
   2=\text{Gripe},\qquad
   3=\text{COVID-19},
   $$

   y se tiene

   $$
   A=
   \begin{bmatrix}
   0.7 & 0.2 & 0.1\\
   0.3 & 0.4 & 0.3\\
   0.2 & 0.3 & 0.5
   \end{bmatrix},
   $$

   entonces los renglones y columnas pueden interpretarse como

   $$
   \begin{array}{c|ccc}
   & \text{Resfriado} & \text{Gripe} & \text{COVID-19}\\
   \hline
   \text{Resfriado} & 0.7 & 0.2 & 0.1\\
   \text{Gripe} & 0.3 & 0.4 & 0.3\\
   \text{COVID-19} & 0.2 & 0.3 & 0.5
   \end{array}
   $$

   Por ejemplo,

   $$
   a_{12}=0.2
   $$

   significa que, si el paciente se encuentra actualmente en el estado **Resfriado**, existe una probabilidad de $0.2$ de que en el siguiente instante pase al estado **Gripe**.

   De manera similar,

   $$
   a_{33}=0.5
   $$

   representa la probabilidad de permanecer en el estado **COVID-19** de un instante al siguiente.

   Como desde cada estado necesariamente se debe realizar alguna transición hacia uno de los posibles estados, la suma de cada renglón de $A$ es igual a 1:

   $$
   \sum_{j=1}^{N} a_{ij}=1.
   $$

3. **$B$ (matriz de emisión):** Describe la relación entre los estados ocultos y las observaciones que pueden generarse desde cada uno de ellos. Cada elemento

   $$
   b_i(k)=P(o_t=k\mid q_t=i)
   $$

   representa la probabilidad de observar el símbolo $k$ cuando el sistema se encuentra en el estado oculto $i$.

   La matriz $B$ tiene dimensiones

   $$
   N\times M,
   $$

   donde:

   - $N$ es el número de estados ocultos.
   - $M$ es el número de observaciones o símbolos posibles.

   En esta matriz:

   - **Cada renglón representa un estado oculto**.
   - **Cada columna representa una posible observación**.
   - El elemento ubicado en el renglón $i$ y la columna $k$ indica la probabilidad de observar el símbolo $k$ cuando el sistema se encuentra en el estado $i$.

   Por ejemplo, si los estados ocultos son

   $$
   1=\text{Resfriado},\qquad
   2=\text{Gripe},\qquad
   3=\text{COVID-19},
   $$

   y las observaciones son

   $$
   0=\text{Tos},\qquad
   1=\text{Fiebre},\qquad
   2=\text{Dolor de garganta},
   $$

   para la matriz

   $$
   B=
   \begin{bmatrix}
   0.4 & 0.4 & 0.2\\
   0.5 & 0.3 & 0.2\\
   0.3 & 0.5 & 0.2
   \end{bmatrix},
   $$

   su interpretación es

   $$
   \begin{array}{c|ccc}
   & \text{Tos} & \text{Fiebre} & \text{Dolor de garganta}\\
   \hline
   \text{Resfriado} & 0.4 & 0.4 & 0.2\\
   \text{Gripe} & 0.5 & 0.3 & 0.2\\
   \text{COVID-19} & 0.3 & 0.5 & 0.2
   \end{array}
   $$

   Por ejemplo,

   $$
   b_2(0)=0.5
   $$

   significa que, dado que el paciente se encuentra en el estado oculto **Gripe**, la probabilidad de observar **Tos** es $0.5$.

   Por otro lado,

   $$
   b_3(1)=0.5
   $$

   significa que, dado que el paciente se encuentra en el estado **COVID-19**, la probabilidad de observar **Fiebre** es $0.5$.

   Es importante distinguir las funciones de $A$ y $B$:

   - La matriz **$A$ relaciona estados con estados**:

     $$
     \text{estado actual}\rightarrow\text{estado siguiente}.
     $$

   - La matriz **$B$ relaciona estados con observaciones**:

     $$
     \text{estado oculto}\rightarrow\text{observación}.
     $$

   Al igual que en $A$, la suma de cada renglón de $B$ es igual a 1, ya que, dado un estado, las probabilidades de todas las posibles observaciones forman una distribución de probabilidad:

   $$
   \sum_{k=1}^{M} b_i(k)=1.
   $$

   ## Variables forward: $\alpha_t(j)$

Las variables $\alpha_t(j)$ se utilizan en el **algoritmo Forward** para calcular de manera eficiente la probabilidad de una secuencia de observaciones en un Modelo Oculto de Markov.

Se define

$$
\alpha_t(j)
=
P(o_1,o_2,\ldots,o_t,\ q_t=j),
$$

es decir, $\alpha_t(j)$ representa la probabilidad conjunta de:

1. haber observado la secuencia

   $$
   o_1,o_2,\ldots,o_t,
   $$

   hasta el instante $t$, y

2. encontrarse en el estado oculto $j$ precisamente en ese instante.

Por lo tanto, $\alpha_t(j)$ **no representa únicamente la probabilidad de estar en el estado $j$**. También incorpora la probabilidad de todas las observaciones que se han producido hasta ese momento.

### 1. Inicialización

Para el primer instante de tiempo,

$$
\alpha_1(j)=\pi_j\,b_j(o_1).
$$

Esta expresión combina dos probabilidades:

$$
\pi_j=P(q_1=j)
$$

y

$$
b_j(o_1)=P(o_1\mid q_1=j).
$$

Por lo tanto,

$$
\alpha_1(j)
=
P(q_1=j)\,
P(o_1\mid q_1=j).
$$

Esto representa la probabilidad de que el sistema **comience en el estado $j$** y, estando en dicho estado, produzca la primera observación $o_1$.

Por ejemplo, si

$$
\pi=
\begin{bmatrix}
0.5 & 0.3 & 0.2
\end{bmatrix}
$$

y la primera observación es

$$
o_1=\text{Tos},
$$

utilizando

$$
B=
\begin{bmatrix}
0.4 & 0.4 & 0.2\\
0.5 & 0.3 & 0.2\\
0.3 & 0.5 & 0.2
\end{bmatrix},
$$

se obtiene

$$
\alpha_1(1)=0.5(0.4)=0.20,
$$

$$
\alpha_1(2)=0.3(0.5)=0.15,
$$

$$
\alpha_1(3)=0.2(0.3)=0.06.
$$

Por lo tanto,

$$
\boldsymbol{\alpha}_1
=
\begin{bmatrix}
0.20 & 0.15 & 0.06
\end{bmatrix}.
$$

### 2. Recursión

Para los siguientes instantes de tiempo se utiliza

$$
\boxed{
\alpha_t(j)
=
\left[
\sum_{i=1}^{N}
\alpha_{t-1}(i)a_{ij}
\right]
b_j(o_t)
}
$$

para

$$
t=2,3,\ldots,T.
$$

Esta expresión puede entenderse en dos pasos.

#### Paso 1: llegar al estado $j$

Primero se calcula

$$
\sum_{i=1}^{N}
\alpha_{t-1}(i)a_{ij}.
$$

Aquí se consideran **todos los estados posibles $i$** en los que el sistema pudo encontrarse en el instante anterior.

Para cada estado $i$,

$$
\alpha_{t-1}(i)
$$

representa la probabilidad acumulada de haber observado la secuencia hasta $t-1$ y encontrarse en $i$, mientras que

$$
a_{ij}
$$

representa la probabilidad de pasar de

$$
i\rightarrow j.
$$

Por tanto,

$$
\alpha_{t-1}(i)a_{ij}
$$

representa la probabilidad de seguir una trayectoria que llega desde el estado $i$ hasta el estado $j$.

Como se puede llegar a $j$ desde cualquiera de los $N$ estados anteriores, se suman todas las posibilidades:

$$
\alpha_{t-1}(1)a_{1j}
+
\alpha_{t-1}(2)a_{2j}
+\cdots+
\alpha_{t-1}(N)a_{Nj}.
$$

#### Paso 2: generar la nueva observación

Una vez que el sistema llega al estado $j$, debe producir la observación correspondiente al instante $t$.

Por ello se multiplica por

$$
b_j(o_t).
$$

Así,

$$
\alpha_t(j)
=
\underbrace{
\left[
\sum_{i=1}^{N}
\alpha_{t-1}(i)a_{ij}
\right]
}_{\text{probabilidad de llegar a }j}
\underbrace{
b_j(o_t)
}_{\text{probabilidad de observar }o_t\text{ desde }j}.
$$

### Ejemplo del cálculo de $\alpha_2(j)$

Supóngase que la segunda observación es

$$
o_2=\text{Fiebre}.
$$

Ya se obtuvo

$$
\boldsymbol{\alpha}_1=
\begin{bmatrix}
0.20 & 0.15 & 0.06
\end{bmatrix}.
$$

Utilizando

$$
A=
\begin{bmatrix}
0.7 & 0.2 & 0.1\\
0.3 & 0.4 & 0.3\\
0.2 & 0.3 & 0.5
\end{bmatrix},
$$

para calcular

$$
\alpha_2(1),
$$

es decir, la probabilidad acumulada de observar

$$
(\text{Tos},\text{Fiebre})
$$

y terminar en el estado **Resfriado**, primero se consideran todas las maneras posibles de llegar a Resfriado:

$$
0.20(0.7)+0.15(0.3)+0.06(0.2).
$$

Por tanto,

$$
0.14+0.045+0.012=0.197.
$$

Como la probabilidad de observar **Fiebre** estando en Resfriado es

$$
b_1(1)=0.4,
$$

entonces

$$
\alpha_2(1)
=
0.197(0.4)
=
0.0788.
$$

Para Gripe,

$$
\alpha_2(2)
=
\left[
0.20(0.2)
+
0.15(0.4)
+
0.06(0.3)
\right](0.3),
$$

por lo que

$$
\alpha_2(2)
=
(0.04+0.06+0.018)(0.3)
=
0.0354.
$$

Finalmente, para COVID-19,

$$
\alpha_2(3)
=
\left[
0.20(0.1)
+
0.15(0.3)
+
0.06(0.5)
\right](0.5),
$$

de donde

$$
\alpha_2(3)
=
(0.02+0.045+0.03)(0.5)
=
0.0475.
$$

Así,

$$
\boldsymbol{\alpha}_2
=
\begin{bmatrix}
0.0788 & 0.0354 & 0.0475
\end{bmatrix}.
$$

### 3. Terminación

Una vez calculados los valores de $\alpha_T(j)$ para el último instante $T$, la probabilidad total de la secuencia de observaciones

$$
O=(o_1,o_2,\ldots,o_T)
$$

se obtiene sumando las probabilidades de terminar en cualquiera de los estados ocultos:

$$
\boxed{
P(O\mid\lambda)
=
\sum_{j=1}^{N}\alpha_T(j)
}
$$

donde

$$
\lambda=(\pi,A,B)
$$

representa el HMM completo.

Por ejemplo, para las dos observaciones anteriores,

$$
O=(\text{Tos},\text{Fiebre}),
$$

se tiene

$$
P(O\mid\lambda)
=
0.0788+0.0354+0.0475
=
0.1617.
$$

Por lo tanto,

$$
P(\text{Tos},\text{Fiebre}\mid\lambda)
=
0.1617.
$$

### Interpretación intuitiva

Puede pensarse en $\alpha_t(j)$ como una **probabilidad acumulada**.

En cada instante se realizan tres operaciones:

$$
\boxed{
\text{probabilidades anteriores}
\rightarrow
\text{transiciones}
\rightarrow
\text{nueva observación}
}
$$

Es decir,

$$
\alpha_{t-1}(i)
\quad\longrightarrow\quad
a_{ij}
\quad\longrightarrow\quad
b_j(o_t).
$$

Para calcular $\alpha_t(j)$:

1. Se consideran todos los estados $i$ desde los cuales se puede llegar a $j$.
2. Se multiplica la probabilidad acumulada de cada estado anterior por su probabilidad de transición $a_{ij}$.
3. Se suman todas las formas posibles de llegar a $j$.
4. Se multiplica el resultado por la probabilidad de que $j$ produzca la observación actual $o_t$.

En forma compacta,

$$
\boxed{
\alpha_t(j)
=
\text{probabilidad de llegar a }j
\times
\text{probabilidad de emitir }o_t\text{ desde }j
}
$$

La principal ventaja del algoritmo Forward es que evita enumerar explícitamente todas las posibles secuencias de estados ocultos, cuyo número crecería exponencialmente con la longitud de la secuencia de observaciones.

> **Importante:** $\alpha_t(j)$ no es igual a $P(q_t=j\mid O)$.  
> $\alpha_t(j)$ es una probabilidad conjunta:

$$
\alpha_t(j)=P(o_1,\ldots,o_t,q_t=j).
$$

In [1]:
%%capture
import sys

# Add the parent directory to the system path to allow importing from modules located there
sys.path.insert(0, "..")

from likelihood.models.hmm import HMM

In [2]:
# Define the parameters of the model
n_states = 3  # Sunny (0), Rainy (1), Cloudy (2)
n_observations = 2  # Walk (0), Shop (1)

# Generate synthetic data from a known HMM
true_pi = np.array([0.4, 0.3, 0.3])
true_A = np.array([[0.7, 0.2, 0.1], [0.2, 0.6, 0.2], [0.1, 0.3, 0.6]])
true_B = np.array([[0.8, 0.2], [0.3, 0.7], [0.5, 0.5]])

rng = np.random.default_rng()


def generate_sequence(pi, A, B, length, rng):
    states = []
    observations = []

    n_states = len(pi)
    n_observations = B.shape[1]
    state = rng.choice(
        n_states,
        p=pi,
    )
    for _ in range(length):
        states.append(state)
        observation = rng.choice(
            n_observations,
            p=B[state],
        )
        observations.append(observation)
        state = rng.choice(
            n_states,
            p=A[state],
        )
    return observations, states


# Generate 20 sequences of length 10
sequences = []
true_states = []
for _ in range(20):
    o, s = generate_sequence(true_pi, true_A, true_B, 10, rng)
    sequences.append(o)
    true_states.append(s)

train_sequences, val_sequences, train_states, val_states = train_test_split(
    sequences, true_states, test_size=0.2, random_state=42
)

print("Data: 20 sequences x 10 observations = 200 data points")
print(f"True pi: {true_pi}")

# Test various model configurations
state_configs = [2, 3, 4]

best_hmm, best_config, history = train_best_hmm(
    train_sequences,
    val_sequences,
    val_states,
    state_configs,
    n_observations=n_observations,
    max_iterations=200,
    n_restarts=10,
)

best_hmm.save_model()

print(f"Best configuration: {best_config}")
print("\nPi:")
print(best_hmm.pi)
print("\nA:")
print(best_hmm.A)
print("\nB:")
print(best_hmm.B)

Best configuration: (3, 2, 200) with accuracy 60.00%
Pi:  [0.35439262 0.24516879 0.40043858]
A:
 [[0.53678304 0.11759566 0.3456213 ]
 [0.24486894 0.60442959 0.15070147]
 [0.25734815 0.25623215 0.4864197 ]]
B:
 [[0.55714163 0.44285837]
 [0.47934544 0.52065456]
 [0.5582844  0.4417156 ]]


In [3]:
hmm = HMM(n_states, n_observations)
hmm = hmm.load_model()
accuracy = hmm.decoding_accuracy(sequences, true_states)
print(f"Decoding Accuracy (model rebuilt): {accuracy:.2f}%")
test_sequence = sequences[3]
predicted_states = hmm.viterbi(test_sequence)
smoothed_probs = hmm.state_probabilities(test_sequence)
total_prob = hmm.sequence_probability(test_sequence)

print(f"Test Sequence: {test_sequence}")
print(f"Predicted States: {predicted_states}")
print(f"Probabilities of hidden states: {smoothed_probs}")
print(f"Total probability: {total_prob:.8f}")

Decoding Accuracy (model rebuilt): 60.00%
Test Sequence: [0, 1, 0, 0, 1]
Predicted States: [0 0 0 0 0]
Probabilities of hidden states: [[0.28873463 0.4565849  0.25468047]
 [0.33941198 0.33264173 0.32794629]
 [0.30965021 0.36871896 0.32163083]
 [0.28682214 0.40581216 0.3073657 ]
 [0.32725088 0.33114961 0.34159951]]
Total probability: [0.32725088 0.33114961 0.34159951]
